"""initial

Revision ID: 4337571b8a8f
Revises: 
Create Date: 2026-08-11 02:35:04.320053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4337571b8a8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_code', sa.String(length=18), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('base_unit', sa.String(length=3), nullable=False),
    sa.Column('plant', sa.String(length=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("material_type IN ('FINISHED_PRODUCT', 'RAW_MATERIAL', 'SEMI_FINISHED', 'PACKAGING', 'AUXILIARY')", name='ck_materials_material_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.create_table('production_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_code', sa.String(length=8), nullable=False),
    sa.Column('resource_name', sa.String(length=50), nullable=False),
    sa.Column('work_center', sa.String(length=8), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_resources_resource_code'), 'production_resources', ['resource_code'], unique=True)
    op.create_table('production_recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_code', sa.String(length=18), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_recipes_recipe_code'), 'production_recipes', ['recipe_code'], unique=True)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=16), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'CREATED'")),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.CheckConstraint("status IN ('CREATED', 'RELEASED', 'IN_PROCESS', 'COMPLETED', 'CLOSED', 'DELIVERED', 'PARTIAL')", name='ck_production_orders_status'),
    sa.CheckConstraint('planned_end > planned_start', name='ck_production_orders_dates'),
    sa.CheckConstraint('planned_quantity > 0', name='ck_production_orders_planned_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_table('recipe_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('component_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['component_material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('work_center', sa.String(length=8), nullable=False),
    sa.Column('operation_description', sa.String(length=200), nullable=False),
    sa.Column('standard_time_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.String(length=16), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('yield_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'CREATED'")),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('CREATED', 'IN_PRODUCTION', 'COMPLETED', 'REWORK', 'SCRAP', 'RELEASED')", name='ck_batches_status'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['production_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=True)
    op.create_table('cost_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('planned_material_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('planned_labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('planned_machine_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')),
    sa.Column('planned_energy_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')),
    sa.Column('planned_total_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')),
    sa.Column('actual_material_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_labor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_machine_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_energy_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_total_cost IS NULL OR actual_total_cost = COALESCE(actual_material_cost, 0) + COALESCE(actual_labor_cost, 0) + COALESCE(actual_machine_cost, 0) + COALESCE(actual_energy_cost, 0)', name='ck_cost_actual_total'),
    sa.CheckConstraint('planned_total_cost = planned_material_cost + planned_labor_cost + planned_machine_cost + planned_energy_cost', name='ck_cost_planned_total'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id')
    )
    op.create_table('material_consumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=3), nullable=False),
    sa.Column('consumption_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=3), nullable=False),
    sa.Column('confirmation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('inspection_lot', sa.String(length=16), nullable=False),
    sa.Column('inspection_status', sa.String(length=20), nullable=False, server_default=sa.text("'PENDING'")),
    sa.Column('pH', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('alcohol_percent', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('co2_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('appearance', sa.String(length=50), nullable=True),
    sa.Column('microbiological_status', sa.String(length=50), nullable=True),
    sa.Column('inspector_notes', sa.Text(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('result_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("inspection_status IN ('PENDING', 'IN_PROGRESS', 'PASSED', 'FAILED', 'REWORK', 'SCRAP')", name='ck_quality_inspections_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_quality_inspections_inspection_lot'), 'quality_inspections', ['inspection_lot'], unique=True)
    op.create_table('non_conformities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('defect_type', sa.String(length=50), nullable=False),
    sa.Column('defect_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.CheckConstraint("disposition IN ('USE_AS_IS', 'REWORK', 'SCRAP', 'RETURN')", name='ck_non_conformities_disposition'),
    sa.CheckConstraint("severity IN ('CRITICAL', 'MAJOR', 'MINOR')", name='ck_non_conformities_severity'),
    sa.ForeignKeyConstraint(['inspection_id'], ['quality_inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('non_conformities')
    op.drop_index(op.f('ix_quality_inspections_inspection_lot'), table_name='quality_inspections')
    op.drop_table('quality_inspections')
    op.drop_table('production_confirmations')
    op.drop_table('material_consumptions')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('recipe_operations')
    op.drop_table('recipe_components')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_production_recipes_recipe_code'), table_name='production_recipes')
    op.drop_table('production_recipes')
    op.drop_index(op.f('ix_production_resources_resource_code'), table_name='production_resources')
    op.drop_table('production_resources')
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
